---
title : "This is a demo simulation for only a few topics and a few users"
n_topics : 2
n_users : 200

n_newsposts : 50 #number of initial posts
n_newsposts_step : 5 # number of new posts that are generated for each step
topic_limit : 3

decay_factor : 0.6 #factor that determines the decrease of relevance of news

update_for_user : true #if true, training matrix will be updated after each users gets a prediciton, if false only once per step

update_user_interest : "none" # none, random, dominant

n_steps : 50
outputfilename : "default.rds"

recommender : "UBCF"
---
