---
title : "This is a demo simulation for only a few topics and a few users"
n_topics : 2
n_users : 200

n_newsposts : 50 #number of initial posts
n_nesposts_step : 10 # number of new posts that are generated for each step
topic_limit : 3

decay_factor : 0.9 #factor that determines the decrease of relevance of news

n_steps : 10
outputfilename : "default.rds"

recommender : "UBCF"
---
