---
title : "This is a demo simulation for only a few topics and a few users"
n_topics : 2
n_users : 200

n_newsposts : 500
topic_limit : 3

n_steps : 100
outputfilename : "default2.rds"

recommender : "POPULAR"
---
